baseURL = 'https://geezforce.github.io/'
languageCode = "en"
defaultContentLanguage = "en"
title = 'C G Giridhar'
theme = "hugo-ficurinia"

# this will be included in the footer after the current year the site is last
# built, followed by the (c) symbol
# you can use markdown inside this field
copyright = "Creative Commons 4.0 - [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.en)"

paginate = 5  # number of articles per page in the index
summaryLength = 30  # number of words for article summaries

[params]
    author = "C G Giridhar"
    description = "Personal website and blog of Giridhar about Computer Science and Life"  # this will be added as metadata

    posts = "posts"  # content directory where to find home page posts; default searches in "posts" and "post"
    showPostsLink = true  # show or hide the link to the simple post list
    extraContentDirs = []  # other content directories to render similarly to the home page
    showcaseDir = "showcase"  # create a content directory that shows a special showcase section in the home page

    # shows a specified single page as a home page, instead of the traditional articles list
    # requires setting `homeSinglePage`
    # goes well with extraContentDirs
    showSinglePageAsHome = false
    homeSinglePage = "/home"

    # It's best to put these icons in the "static" folder of your site
    logo = "/avatar/github-avatar.png"
    favicon = "/avatar/github-avatar.png"  # 32x32
    faviconIco = "/avatar/github-avatar.png"  # 32x32
    appletouch = "/avatar/github-avatar.png"  # 180x180
    svgicon = "/avatar/github-avatar.png"
    icon512 = "/avatar/github-avatar.png"  # 512x512 png image


    logoRightOfTitle = false  # positions the logo to the right of the title; default: false

    showTags = true  # show the Tags menu item; default true
    showRss = false  # show the link for the RSS feed; default true

    imageInArticlePreview = true  # show images in article preview; default false
    fitImageInArticlePreview = true  # make article preview images fit the article preview instead of getting cropped
    articleSummary = true  # show a summary in article preview; default true
    relatedArticlesNum = 2 
    forceRedirect = true

    fontFamily = "JetBrains Mono"  # changes the font, default "JetBrains Mono"
    titleFontFamily = "JetBrains Mono"  # font used for titles and headings
    monospaceFontFamily = "JetBrains Mono"  # changes the monospace font for code, default "JetBrains Mono"

    # multipliers applied to font sizes, useful for custom fonts that may be too big or too small
    titleFontSizeMultiplier = 1.0
    mainFontSizeMultiplier = 1.0
    monoFontSizeMultiplier = 1.0

    contentWidth = "1000px"  # maximum width of the site content, css syntax

    paperCards = false  # enable paper card style; default false
    buttonTags = false  # enable button tag style; default false
    tagsInArticlePreview = true  # enable tags list in the article preview card
    gridView = false  # show post list as a grid. goes well with paperCards
    bigArticleTitle = false  # makes the title in the single article view bigger
    navtype = "standard"  # changes the style of the pagination, available styles are: "standard", "circles"
    enableShadow = true  # shows a shadow around some elements
    menuStyle = "standard"  # changes the style of the main site navigation menu, available styles are: "standard", "buttons"
    inputStyle = "standard" # changes the style of inputs (like the searchbar), available styles are: "standard", "buttons"

    enableSearch = true  # enable search page
    searchbarEverywhere = true  # if the searchbar should be shown in every page; requires enableSearch
    searchMenuLink = false  # add a search link to the navigation menu; requires enableSearch
    mobileHamburgerNav = false  # alternative hamburger menu layout for the main nav menu when screen is small

    enableFeatured = false  # enable a particular view for articles marked as featured (featured: true in the article frontmatter)

    underlineTitleLinks = false  # show an underline also for links that are titles



    [menu]
    # these links will be added to the main navigation menu, sorted by weight
    # other elements in this menu are added automatically from the "pages" folder
    # the folder it will look into can be customized with the pages variable
    # in params above
    # these links (menu.icons) will be added as icon links below the main nav
    [[menu.icons]]
        identifier = "email"
        name = "Mail"
        url = "mailto:girigov39@gmail.com"
        weight = 10
    [[menu.icons]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/GeezFORCE"
        weight = 20    
    [[menu.icons]]
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/c-g-giridhar-887b00173/"
        weight = 30
    [[menu.icons]]
        identifier = "twitter"
        name = "Twitter"
        url = "https://twitter.com/GovindGiridhar"
        weight = 40

[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 1
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    lineNumbersInTable = false
    tabWidth = 4
    style = "dracula"


# this section is necessary if you want infinite scrolling
# it allows to output the article list as paged JSON so that "pages" can be retrieved via javascript
[outputs]
    home = ["HTML", "JSON"]
